spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # Swagger 에러 조치를 위한 설정
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace
server:
  servlet:
    context-path: /api